# Generated by Django 3.1.2 on 2021-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, default='Banck name', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='bik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='correspondent_bank_account',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_entity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kpp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_address',
            field=models.ManyToManyField(blank=True, related_name='user_addresses_legal', to='account.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_org',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='orgn',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
