# Generated by Django 3.1.2 on 2021-07-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20210728_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bik',
        ),
        migrations.RemoveField(
            model_name='user',
            name='correspondent_bank_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_entity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_org',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orgn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
