# Generated by Django 3.1.2 on 2021-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_auto_20210729_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, default='Banck name', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.CharField(default='00000000000000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='bik',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='correspondent_bank_account',
            field=models.CharField(default='00000000000000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='is_entity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kpp',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_address',
            field=models.ManyToManyField(blank=True, related_name='user_addresses_legal', to='account.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_org',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='orgn',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
