# Generated by Django 3.1.2 on 2021-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20210729_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_entity',
            field=models.BooleanField(default=False),
        ),
    ]
