# Generated by Django 3.1.2 on 2021-07-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20210729_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='legal_address',
            new_name='legal_addres',
        ),
    ]
